version: "3"

services:
    loki:
        image: grafana/loki:master
        ports:
            - 3100:3100
        command: -config.file=/etc/loki/local-config.yaml

    grafana:
        image: grafana/grafana:master
        ports:
            - "3000:3000"
