services:
  
  mongodb:
      image: mongo
      ports:
        - "27017:27017"
      volumes:
        - mongo_data:/data/db

  mongo-express:
    image: mongo-express    
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpressuser

volumes:
  mongo_data:
  
