<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup>
      <!-- Enable NuGet package auditing -->
      <NuGetAudit>true</NuGetAudit>

      <!-- Audit direct and transitive packages -->
      <NuGetAuditMode>all</NuGetAuditMode>

      <!-- Report low, moderate, high and critical advisories -->
      <NuGetAuditLevel>low</NuGetAuditLevel>

      <!-- Fails the build on CI or on release when a vulnerability is detected -->
      <WarningsAsErrors>NU1900;NU1901;NU1902;NU1903;NU1904</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.WebSockets" Version="2.3.0" />
    <PackageReference Include="Microsoft.IO.RecyclableMemoryStream" Version="3.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

</Project>
