version: '3.4'
services:

  elasticsearch:
    image: "elasticsearch:7.8.1"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: "kibana:7.8.1"
    ports:
      - "5601:5601"
