[[inputs.statsd]]
  service_address = ":8125"
  datadog_extensions = true
  metric_separator = "_"
  allowed_pending_messages = 10000
  percentile_limit = 2

[[outputs.file]]
  files = ["stdout"]
  data_format = "influx"
