<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
      <!-- Enable NuGet package auditing -->
      <NuGetAudit>true</NuGetAudit>

      <!-- Audit direct and transitive packages -->
      <NuGetAuditMode>all</NuGetAuditMode>

      <!-- Report low, moderate, high and critical advisories -->
      <NuGetAuditLevel>low</NuGetAuditLevel>

      <!-- Fails the build on CI or on release when a vulnerability is detected -->
      <WarningsAsErrors>NU1900;NU1901;NU1902;NU1903;NU1904</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.31.1" />
    <PackageReference Include="Grpc.Net.Client" Version="2.71.0" />
    <PackageReference Include="Grpc.Tools" Version="2.72.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NBomber.Data" Version="6.1.1" />
    <PackageReference Include="System.Text.Json" Version="9.0.7" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\simulator.proto" GrpcServices="Client" />
  </ItemGroup>

</Project>
