{
 "title": "NBomber dashboard by Parimatch Tech",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "group_time", "query": "5,10,15,30,45,60" },
   { "name": "fill", "label": "Fill", "query": "null, none" },
   {
    "name": "metric",
    "label": "Metric",
    "query": "mean,min,max,percent50,percent75,percent95,percent99"
   },
   {
    "name": "test_name",
    "label": "TestName",
    "query": "SHOW TAG VALUES FROM \"nbomber__simulation.value\" WITH KEY = \"test_name\""
   },
   {
    "name": "scenario",
    "label": "Scenario",
    "query": "SHOW TAG VALUES WITH KEY = \"scenario\"  WHERE test_name =~ /$test_name/ AND pipeline =~ /$pipeline/"
   },
   {
    "name": "step",
    "label": "Step",
    "query": "SHOW TAG VALUES WITH KEY = \"step\"  WHERE test_name =~ /$test_name$/ AND pipeline =~ /$pipeline/ AND scenario =~ /$scenario$/"
   },
   {
    "name": "pipeline",
    "label": "Pipeline",
    "query": "SELECT DISTINCT(\"pipeline\") FROM (SELECT \"pipeline\",\"value\" FROM \"nbomber__simulation.value\" WHERE test_name =~ /$test_name/)"
   },
   {
    "name": "build_source",
    "label": "Build source",
    "query": "SHOW TAG KEYS FROM \"nbomber__simulation.value\" WHERE test_name=~ /$test_name/"
   },
   {
    "name": "build",
    "label": "Build",
    "query": "SHOW TAG VALUES FROM \"nbomber__simulation.value\" WITH KEY =~ /build_$build_source/ WHERE pipeline =~ /$pipeline/"
   },
   {
    "name": "build_history",
    "label": "Build history",
    "query": "SHOW TAG VALUES FROM \"nbomber__simulation.value\" WITH KEY =~ /build_$build_source/ "
   }
  ]
 },
 "panels": [
  {
   "title": "Throughput(RPS) by Scenario(s) and Step(s)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "OK - $tag_scenario - $tag_step",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"value\") FROM \"nbomber__ok.request.rps\" WHERE test_name =~ /$test_name/ AND scenario =~ /$scenario$/ AND step =~ /$step$/ AND pipeline =~ /$pipeline/ AND build_$build_source =~ /$build/ AND  $timeFilter GROUP BY scenario, step, time($__interval) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "FAIL  - $tag_scenario - $tag_step",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"value\") FROM \"nbomber__fail.request.rps\" WHERE test_name =~ /$test_name/ AND scenario =~ /$scenario$/ AND step =~ /$step$/ AND pipeline =~ /$pipeline/ AND build_$build_source =~ /$build/ AND  $timeFilter GROUP BY scenario, step, time($__interval) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active users by Scenario(s)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Scenario - $tag_scenario",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"value\") FROM \"nbomber__simulation.value\" WHERE test_name =~ /$test_name/ AND scenario =~ /$scenario$/ AND pipeline =~ /$pipeline/ AND build_$build_source =~ /$build/ AND  $timeFilter GROUP BY scenario, time($__interval) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Requests OK by Scenario(s) and Step(s)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(value) FROM \"nbomber__ok.request.count\" WHERE test_name =~ /$test_name/ AND scenario =~ /$scenario$/ AND step =~ /$step$/ AND pipeline =~ /$pipeline/ AND build_$build_source =~ /$build/ AND  $timeFilter  FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Requests FAIL by Scenario(s) and Step(s)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(value) FROM \"nbomber__fail.request.count\" WHERE test_name =~ /$test_name/ AND scenario =~ /$scenario$/ AND step =~ /$step$/ AND pipeline =~ /$pipeline/ AND build_$build_source =~ /$build/ AND  $timeFilter  FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transferred bytes OK by Scenario(s) and Step(s)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(value) FROM \"nbomber__ok.datatransfer.allbytes\" WHERE test_name =~ /$test_name/ AND scenario =~ /$scenario$/ AND step =~ /$step$/ AND pipeline =~ /$pipeline/ AND build_$build_source =~ /$build/ AND  $timeFilter FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transferred bytes FAIL by Scenario(s) and Step(s)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(value) FROM \"nbomber__fail.datatransfer.allbytes\" WHERE test_name =~ /$test_name/ AND scenario =~ /$scenario$/ AND step =~ /$step$/ AND pipeline =~ /$pipeline/ AND build_$build_source =~ /$build/ AND  $timeFilter FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of Failed request by Scenario and Step",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_scenario - $tag_step",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(value) FROM \"nbomber__fail.request.count\" WHERE test_name =~ /$test_name$/ AND scenario =~ /$scenario$/ AND step =~ /$step$/ AND pipeline =~ /$pipeline/ AND  $timeFilter GROUP BY scenario, step, time($__interval) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response Times (Latency) by Scenario(s) and Step(s) - $metric",
   "type": "graph",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "OK - $tag_scenario - $tag_step",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"value\") FROM \"nbomber__ok.latency.$metric\" WHERE test_name =~ /$test_name/ AND scenario =~ /$scenario$/ AND step =~ /$step$/ AND pipeline =~ /$pipeline/ AND build_$build_source =~ /$build/ AND  $timeFilter GROUP BY scenario, step, time($__interval) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "FAIL - $tag_scenario - $tag_step",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"value\") FROM \"nbomber__fail.latency.$metric\" WHERE test_name =~ /$test_name/ AND scenario =~ /$scenario$/ AND step =~ /$step$/ AND pipeline =~ /$pipeline/ AND build_$build_source =~ /$build/ AND  $timeFilter GROUP BY scenario, step, time($__interval) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transferred bytes by Scenario(s) and Step(s)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "OK - $tag_scenario - $tag_step",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(value)/5 FROM \"nbomber__ok.datatransfer.allbytes\" WHERE test_name =~ /$test_name/ AND scenario =~ /$scenario$/ AND step =~ /$step$/ AND pipeline =~ /$pipeline/ AND build_$build_source =~ /$build/ AND  $timeFilter GROUP BY scenario, step, time($__interval) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "FAIL - $tag_scenario - $tag_step",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(value)/5 FROM \"nbomber__fail.datatransfer.allbytes\" WHERE test_name =~ /$test_name/ AND scenario =~ /$scenario$/ AND step =~ /$step$/ AND pipeline =~ /$pipeline/ AND build_$build_source =~ /$build/ AND  $timeFilter GROUP BY scenario, step, time($__interval) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Summary - OK",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \nlast(\"Count - All\") AS \"Count - All\",  \nlast(\"Count - OK\") AS \"Count - OK\", \nlast(rps) AS Rps, \nlast(\"Latency Min\") AS \"Latency Min\", \nlast(\"Latency Max\") AS \"Latency Max\", \nlast(\"Latency Mean\") AS \"Latency Mean\",\nlast(\"Latency p50\") AS \"Latency p50\",\nlast(\"Latency p75\") AS \"Latency p75\",\nlast(\"Latency p95\") AS \"Latency p95\",\nlast(\"Latency p99\") AS \"Latency p99\",\nlast(\"All bytes\") AS \"All bytes\"\nFROM (SELECT \n           \"all\" AS \"Count - All\",\n\t   count AS \"Count - OK\",\n\t   rps,\n\t   scenario,\n\t   step\nFROM \"nbomber__ok.summary\" WHERE test_name =~ /$test_name/ AND scenario =~ /$scenario$/ AND step =~ /$step$/ AND pipeline =~ /$pipeline/ AND build_$build_source =~ /$build/ AND $timeFilter AND stat_type = 'request' FILL($fill)),\n(SELECT \n           min AS \"Latency Min\",\n\t   max AS \"Latency Max\",\n\t   mean AS \"Latency Mean\",\n           percent50 AS \"Latency p50\",\n           percent75 AS \"Latency p75\",\n           percent95 AS \"Latency p95\",\n           percent99 AS \"Latency p99\",\n\t   scenario,\n\t   step\nFROM \"nbomber__ok.summary\" WHERE test_name =~ /$test_name/ AND scenario =~ /$scenario$/ AND step =~ /$step$/ AND pipeline =~ /$pipeline/ AND build_$build_source =~ /$build/ AND $timeFilter AND stat_type = 'latency' FILL($fill)),\n(SELECT \n           allbytes AS \"All bytes\",\n\t   scenario,\n\t   step\nFROM \"nbomber__ok.summary\" WHERE test_name =~ /$test_name/ AND scenario =~ /$scenario$/ AND step =~ /$step$/ AND pipeline =~ /$pipeline/ AND build_$build_source =~ /$build/ AND $timeFilter AND stat_type = 'datatransfer' FILL($fill)) GROUP BY scenario, step FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Summary - FAIL",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \nlast(\"Count - All\") AS \"Count - All\",  \nlast(\"Count - FAIL\") AS \"Count - FAIL\", \nlast(rps) AS Rps, \nlast(\"Latency Min\") AS \"Latency Min\", \nlast(\"Latency Max\") AS \"Latency Max\", \nlast(\"Latency Mean\") AS \"Latency Mean\",\nlast(\"Latency p50\") AS \"Latency p50\",\nlast(\"Latency p75\") AS \"Latency p75\",\nlast(\"Latency p95\") AS \"Latency p95\",\nlast(\"Latency p99\") AS \"Latency p99\",\nlast(\"All bytes\") AS \"All bytes\"\nFROM (SELECT \n           \"all\" AS \"Count - All\",\n\t   count AS \"Count - FAIL\",\n\t   rps,\n\t   scenario,\n\t   step\nFROM \"nbomber__fail.summary\" WHERE test_name =~ /$test_name/ AND scenario =~ /$scenario$/ AND step =~ /$step$/ AND pipeline =~ /$pipeline/ AND build_$build_source =~ /$build/ AND $timeFilter AND stat_type = 'request' FILL($fill)),\n(SELECT \n           min AS \"Latency Min\",\n\t   max AS \"Latency Max\",\n\t   mean AS \"Latency Mean\",\n           percent50 AS \"Latency p50\",\n           percent75 AS \"Latency p75\",\n           percent95 AS \"Latency p95\",\n           percent99 AS \"Latency p99\",\n\t   scenario,\n\t   step\nFROM \"nbomber__fail.summary\" WHERE test_name =~ /$test_name/ AND scenario =~ /$scenario$/ AND step =~ /$step$/ AND pipeline =~ /$pipeline/ AND build_$build_source =~ /$build/ AND $timeFilter AND stat_type = 'latency' FILL($fill)),\n(SELECT \n           allbytes AS \"All bytes\",\n\t   scenario,\n\t   step\nFROM \"nbomber__fail.summary\" WHERE test_name =~ /$test_name/ AND scenario =~ /$scenario$/ AND step =~ /$step$/ AND pipeline =~ /$pipeline/ AND build_$build_source =~ /$build/ AND $timeFilter AND stat_type = 'datatransfer' FILL($fill)) GROUP BY scenario, step FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}